### ISSUE TITLE
csv,conf 6 - Feb 28

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Epistemological-Directories#5]
- [x] Initiate manuscript

- [x] @jesparent  Review

- [x]  Submit
- [x] ... Wait on Response

**Comment by Orthogonal-Research-Lab** [comment]
Had to reduce the wordcount to 300. This version is in the Google Doc below the full version.

**Comment by jesparent** [comment]
rejected (bc we were too similar to last year?)
